export enum MapFilterEnum {
    WHITE_DENSITY = 'WHITE_DENSITY',
    BLACK_DENSITY = 'BLACK_DENSITY',
    HISPANIC_DENSITY = 'HISPANIC_DENSITY',
    ASIAN_DENSITY = 'ASIAN_DENSITY',
    NATIVE_AMERICAN_DENSITY = 'NATIVE_AMERICAN_DENSITY',
    PACIFIC_ISLANDER_DENSITY = 'PACIFIC_ISLANDER_DENSITY',
    OTHER_DENSITY = 'OTHER_DENSITY',
    BIRACIAL_DENSITY = 'BIRACIAL_DENSITY',
    PRES_2016 = 'MAP_FILTER_PRES_2016',
    HOUSE_2016 = 'MAP_FILTER_HOUSE_2016',
    HOUSE_2018 = 'MAP_FILTER_HOUSE_2018',
    SENATE_2016 = 'MAP_FILTER_SENATE_2016',
    SENATE_2018 = 'MAP_FILTER_SENATE_2018',
    DEFAULT = 'MAP_FILTER_PLAIN'
}

export enum ViewLevelEnum {
    PRECINCTS = 'VIEW_LEVEL_PRECINCTS',
    OLD_DISTRICTS = 'VIEW_LEVEL_OLD_DISTRICTS',
    NEW_DISTRICTS = 'VIEW_LEVEL_NEW_DISTRICTS'
}

export enum ElectionEnum {
    PRES_16 = 'ELECTION_PRES_16',
    HOUSE_16 = 'ELECTION_HOUSE_16',
    HOUSE_18 = 'ELECTION_HOUSE_18'
}